CREATE TABLE routes (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    order_ids TEXT NOT NULL,
    cost BIGINT UNSIGNED NOT NULL,
    distance BIGINT UNSIGNED NOT NULL,
    time BIGINT UNSIGNED NOT NULL
);